#pragma once

#if defined(TASK_SWITCH_NO_OS_DETECTION)
    #define EECONFIG_MODULE_TASK_SWITCH_DATA_SIZE 15
#else
    #define EECONFIG_MODULE_TASK_SWITCH_DATA_SIZE 17
#endif // TASK_SWITCH_NO_OS_DETECTION
