#pragma once

#include "quantum.h"
#include "rgb_helpers.h"

#if !defined(PLODAH_RGBINDICATORS_MODS_HSV)
    #define PLODAH_RGBINDICATORS_MODS_HSV HSV_WHITE
#endif // PLODAH_RGBINDICATORS_MODS_HSV

#if !defined(PLODAH_RGBINDICATORS_GUILOCK_HSV)
    #define PLODAH_RGBINDICATORS_GUILOCK_HSV HSV_RED
#endif // PLODAH_RGBINDICATORS_GUILOCK_HSV

#if !defined(PLODAH_RGBINDICATORS_DYNMACRO_HSV)
    #define PLODAH_RGBINDICATORS_DYNMACRO_HSV HSV_RED
#endif // PLODAH_RGBINDICATORS_DYNMACRO_HSV

#if !defined(PLODAH_RGBINDICATORS_CAPS_HSV)
    #define PLODAH_RGBINDICATORS_CAPS_HSV HSV_RED
#endif // PLODAH_RGBINDICATORS_CAPS_HSV


#if !defined(PLODAH_RGBINDICATORS_NUM_HSV)
    #define PLODAH_RGBINDICATORS_NUM_HSV HSV_RED
#endif // PLODAH_RGBINDICATORS_NUM_HSV

#if !defined(PLODAH_RGBINDICATORS_SCRL_HSV)
    #define PLODAH_RGBINDICATORS_SCRL_HSV HSV_RED
#endif // PLODAH_RGBINDICATORS_SCRL_HSV

#if !defined(PLODAH_RGBINDICATORS_LAYER_HSV)
    #define PLODAH_RGBINDICATORS_LAYER_HSV HSV_PINK
#endif // PLODAH_RGBINDICATORS_LAYER_HSV

#if !defined(PLODAH_RGBINDICATORS_LAYER_STARTING)
    #define PLODAH_RGBINDICATORS_LAYER_STARTING 0
#endif // PLODAH_RGBINDICATORS_LAYER_STARTING

#if !defined(PLODAH_RGBINDICATORS_MINVAL)
    #define PLODAH_RGBINDICATORS_MINVAL 63
#endif // PLODAH_RGBINDICATORS_MINVAL

#if !defined(PLODAH_RGBINDICATORS_MSJIGGLER_HSV)
    #define PLODAH_RGBINDICATORS_MSJIGGLER_HSV HSV_ORANGE
#endif // !defined(PLODAH_RGBINDICATORS_MSJIGGLER_HSV)

#if !defined(PLODAH_RGBINDICATORS_MSJIGGLERINTRO_HSV)
    #define PLODAH_RGBINDICATORS_MSJIGGLERINTRO_HSV HSV_MAGENTA
#endif // !defined(MSJIGGLER_NOINTRO) && !defined(PLODAH_RGBINDICATORS_MSJIGGLERINTRO_HSV)

#if !defined(PLODAH_RGBINDICATORS_TYPING_HSV)
    #define PLODAH_RGBINDICATORS_TYPING_HSV HSV_RED
#endif //PLODAH_RGBINDICATORS_TYPING_HSV

#if !defined(PLODAH_RGBINDICATORS_TYPING_DURATION)
    #define PLODAH_RGBINDICATORS_TYPING_DURATION 1000
#endif //PLODAH_RGBINDICATORS_TYPING_DURATION

#if defined(PLODAH_RGBINDICATORS_TYPING_INDEX)
    bool plodah_rgbindicators_typingindicator_active = false;
    uint16_t plodah_rgbindicators_typingindicator_timer = 0;

    void housekeeping_task_rgb_indicators(void);
    bool process_record_rgb_indicators(uint16_t keycode, keyrecord_t *record);
#endif // PLODAH_RGBINDICATORS_TYPING_INDEX

#if defined(DYNAMIC_MACRO_ENABLE) && defined(PLODAH_RGBINDICATORS_DYNMACRO_INDEX)
    extern bool is_dynamic_macro_recording;
#endif // DYNAMIC_MACRO_ENABLE